[package]
name = "hashids"
version = "1.0.0"
authors = [ "charsyam <charsyam@gmail.com>", "andixlm <andixev@gmail.com>" ]
edition = "2021"
license = "MIT"

include = [
  "**/*.rs",
  "Cargo.toml",
]

[dependencies]
regex = "1.5"
thiserror = "1.0"
